import type { RecipeIngredient, ResearchResult } from "@/lib/types";
import { formatGrams, formatMl } from "@/lib/calc/units";

const qty = (i: RecipeIngredient) =>
  [i.grams != null ? formatGrams(i.grams) : null, i.ml != null ? formatMl(i.ml) : null, i.householdMeasure].filter(Boolean).join(" / ");

/** Plain-text/Markdown export with full source attribution. */
export function recipeToMarkdown(result: ResearchResult, ingredients: RecipeIngredient[] = result.recipe.ingredients): string {
  const r = result.recipe;
  const o = r.overview;
  const groups = [...new Set(ingredients.map((i) => i.group))];
  const lines: string[] = [
    `# ${r.name}`,
    "",
    r.summary,
    "",
    `- Cake: ${o.cakeType}`,
    `- Finished weight: ~${o.finishedWeightGrams} g · Servings: ${o.servings}`,
    `- Difficulty: ${o.difficulty}`,
    `- Prep: ${o.prepMinutes} min · Bake: ${o.bakeMinutesMin}–${o.bakeMinutesMax} min · Total: ${o.totalMinutes} min`,
    `- Pan: ${o.panSize}${o.panCount > 1 ? ` × ${o.panCount}` : ""}`,
    `- Oven: ${o.ovenTempC}°C / ${o.ovenTempF}°F`,
    o.applianceNotes ? `- Appliance notes: ${o.applianceNotes}` : "",
    `- Texture: ${o.expectedTexture}`,
    "",
    "## Ingredients",
  ];
  for (const g of groups) {
    lines.push("", `### ${g}`);
    for (const i of ingredients.filter((x) => x.group === g)) lines.push(`- ${i.name} — ${qty(i)}${i.notes ? ` (${i.notes})` : ""}`);
  }
  lines.push("", "## Method");
  r.method.forEach((m, n) => lines.push(`${n + 1}. **${m.title}.** ${m.text}${m.why ? ` _Why: ${m.why}_` : ""}`));
  if (r.whyItWorks.length) {
    lines.push("", "## Why this recipe works");
    r.whyItWorks.forEach((w) => lines.push(`- **${w.topic}:** ${w.explanation}`));
  }
  if (r.frostingNotes) lines.push("", "## Frosting notes", r.frostingNotes);
  if (r.storage) lines.push("", "## Storage", r.storage);
  if (r.warnings.length) {
    lines.push("", "## Notes & caveats");
    r.warnings.forEach((w) => lines.push(`- ${w}`));
  }
  lines.push(
    "",
    "## Sources researched",
    "This recipe was developed by comparing the techniques, ratios and methods used across the sources below.",
    "",
  );
  for (const s of result.sources.filter((x) => x.role && x.role !== "not_used")) {
    lines.push(`- ${s.sourceName} — ${s.title}${s.author ? ` by ${s.author}` : ""}: ${s.url}`);
  }
  lines.push(
    "",
    `Research confidence: ${result.confidence.level} · ${result.confidence.recipesCompared} recipes compared · researched ${new Date(result.researchedAt).toLocaleDateString()}`,
    "Generated by CakeRecipe Finder.",
  );
  return lines.filter((l, i, a) => !(l === "" && a[i - 1] === "")).join("\n");
}

export function downloadText(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "recipe";
